### ISSUE TITLE
Open Source Contributions that no longer work

### ISSUE THREAD

**Issue by mishmanners** [TwilioQuest/twilioquest-resources#2]
In the "Contributing to Open Source: Another One" quest, under the "Help" tab there are few resources to help find open source projects.

This link no longer works:
- [Issues Hub](http://issuehub.io/?utm_source=twilioquest-3)

Maybe replace it with the [GitHub Trending topics link](https://github.com/trending). Just a suggestion. Feel free to add any other cool links. Just thought you'd like to know about the missing/broken/inactive link.

**Comment by joenash** [comment]
Thanks @MishManners! Will get this link issue reported to the devs and see what we can do 💖

**Comment by mishmanners** [comment]
Thanks!

**Comment by MarvelProgramming** [comment]
Fixed in https://github.com/TwilioQuest/twilioquest-open-source/pull/7
